# Change the default logo inside the webmail and on the login screen
# This playbook is not required to run for a 100% install. To skip, just don't
# inform the vars zmlogologin and zmlogoapp.
#  WARNING: It's required to use this playbook both files: The logo for the
#           webmail and the logo for the login screen.

- name: Send the logo file (LOGIN) from your PC to the Server
  copy:
    src: '{{ zmlogologin }}'
    dest: /opt/zimbra/jetty/webapps/zimbra/img/logoLoginBanner.png
    owner: zimbra
    group: zimbra
    mode: 0644

- name: Send the logo file (WEBMAIL) from your PC to the Server
  copy:
    src: '{{ zmlogoapp }}'
    dest: /opt/zimbra/jetty/webapps/zimbra/img/logoAppBanner.png
    owner: zimbra
    group: zimbra
    mode: 0644

- name: Configure the Zimbra Server to find the new logos
  shell: './zmprov md {{ domain }} zimbraSkinLogoURL https://{{ hostname }}.{{ domain }}'
  args:
    chdir: /opt/zimbra/bin
  become: true
  become_user: zimbra

- name: Configure the path for the login logo file
  shell: './zmprov md {{ domain }} zimbraSkinLogoLoginBanner /img/logoLoginBanner.png'
  args:
    chdir: /opt/zimbra/bin
  become: true
  become_user: zimbra

- name: Configure the path for the webmail logo file
  shell: './zmprov md {{ domain }} zimbraSkinLogoAppBanner /img/logoAppBanner.png'
  args:
    chdir: /opt/zimbra/bin
  become: true
  become_user: zimbra
